/*
 * WhenExecutor.h
 *
 *  Created on: Feb 27, 2018
 *      Author: Alti
 */

#ifndef WCI_BACKEND_INTERPRETER_EXECUTORS_WHENEXECUTOR_H_
#define WCI_BACKEND_INTERPRETER_EXECUTORS_WHENEXECUTOR_H_





#endif /* WCI_BACKEND_INTERPRETER_EXECUTORS_WHENEXECUTOR_H_ */
